# Generated by Django 5.1.4 on 2025-01-17 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactoryModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("hourly_production", models.IntegerField()),
                ("hourly_energy", models.IntegerField()),
                ("workforce", models.IntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HabitatModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("species", models.CharField(max_length=50)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaveGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.dataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectorTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("sunlight_percent", models.IntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.savegame",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.sectortemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("population", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.savegame",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.habitatmodule",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.factorymodule",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "storage",
                    models.CharField(
                        choices=[
                            ("C", "Container"),
                            ("L", "Liquid"),
                            ("S", "Solid"),
                        ],
                        max_length=1,
                    ),
                ),
                ("volume", models.IntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.dataset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="factorymodule",
            name="ware",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="x4.ware"
            ),
        ),
        migrations.CreateModel(
            name="WareOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "factory_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.factorymodule",
                    ),
                ),
                (
                    "ware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="x4.ware",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="habitatmodule",
            constraint=models.UniqueConstraint(
                fields=("name", "capacity", "species"), name="Global unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectortemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "dataset"), name="No duplicate sectors"
            ),
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                fields=("template", "game"),
                name="No duplicate sector templates",
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("name", "game"), name="No duplicate stations"
            ),
        ),
        migrations.AddConstraint(
            model_name="habitat",
            constraint=models.UniqueConstraint(
                fields=("module", "station"), name="Unique Habitats"
            ),
        ),
        migrations.AddConstraint(
            model_name="factory",
            constraint=models.UniqueConstraint(
                fields=("module", "station"), name="Unique Factory"
            ),
        ),
    ]
