# Generated by Django 5.1.4 on 2024-12-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
