# Generated by Django 5.1.4 on 2024-12-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='No duplicate sectors',
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('name', 'game'), name='No duplicate sector templates'),
        ),
        migrations.AddField(
            model_name='sectortemplate',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x4.dataset'),
        ),
        migrations.AddConstraint(
            model_name='sectortemplate',
            constraint=models.UniqueConstraint(fields=('name', 'dataset'), name='No duplicate sectors'),
        ),
    ]
