# Generated by Django 5.1.4 on 2025-01-13 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("x4", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wareorder",
            old_name="factory",
            new_name="factory_module",
        ),
    ]
