# Generated by Django 5.1.4 on 2025-01-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x4", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectortemplate",
            name="sunlight_percent",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
