# Generated by Django 5.1.4 on 2024-12-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x4', '0002_habitattemplate_habitat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HabitatTemplate',
            new_name='HabitatModules',
        ),
    ]
