# Generated by Django 5.1.4 on 2024-12-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x4", "0002_station"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("name", "game"), name="No duplicate stations"
            ),
        ),
    ]
