# Generated by Django 5.1.4 on 2024-12-15 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("x4", "0003_rename_habitattemplate_habitatmodules"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HabitatModules",
            new_name="HabitatModule",
        ),
    ]
