# Generated by Django 5.1.4 on 2024-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x4", "0003_station_no_duplicate_stations"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                fields=("name", "game"), name="No duplicate sectors"
            ),
        ),
    ]
